spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://HEALTHCARE-SERVICE
          predicates:
            Path= /api/v1/**
        - id: r2
          uri: lb://BASICDISEASEPREDICTION-SERVICE
          predicates:
            Path= /**
        - id: r3
          uri: lb://CANCERPREDICTION-SERVICE
          predicates:
            Path= /predict
        - id: r4
          uri: lb://DIABETESPREDICTION-SERVICE
          predicates:
            Path= /predict
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE